services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - ./storage:/verdaccio/storage
      - ./config.yaml:/verdaccio/conf/config.yaml:ro
    environment:
      - VERDACCIO_PORT=4873
    restart: unless-stopped
